version: "2"
run:
  go: "1.23"
linters:
  enable:
    - dogsled
    - dupl
    - gosec
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    staticcheck:
      checks:
        - "-QF1008" # Disable the "could remove embedded field" check
    gosec:
      excludes:
        - G306 # WriteFile with 0644 is appropriate for config files
    dupl:
      threshold: 200 # Allow more similarity for type-specific loaders
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
